FROM node:14-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --no-optional && npm cache clean --force

COPY . ./

EXPOSE 8080

CMD [ "npm", "run", "serve" ]

ENV PYTHONUNBUFFERED=1
ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1
RUN apk add --update --no-cache python3 python3-dev && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools wheel

RUN apk add gcc musl-dev libffi-dev postgresql-dev g++ jpeg-dev zlib-dev build-base
RUN pip3 install -r requirements.txt
